# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Deep Thummar
title: Senior Software Developer
email: deepthumar224@gmail.com
# email_title: Email (Email title override)
phone: +91 6355489829
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  deep-thumar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: deepthummar.in
linkedin_username: thumar-deep-818489341
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  As a results-driven Senior Software Developer with over 4 years of hands-on experience, I specialize in architecting and optimizing robust web applications that deliver measurable business value. My expertise spans modern frontend frameworks like ReactJS and AngularJS, and extends to backend technologies including .NET Core, .NET MVC, Web API, and Node.js. I thrive in dynamic, agile environments, consistently delivering scalable and maintainable solutions.
  
  I am recognized for my ability to lead teams, mentor junior developers, and collaborate across functions to deliver complex projects ahead of deadlines. My technical prowess is complemented by a passion for clean code, best practices, and continuous learning. Key accomplishments include:

    - Leading a team of 5 developers to deliver a major project two weeks ahead of schedule
    
    - Optimizing APIs to reduce response times by 25%
    
    - And earning multiple “Shining Star” and “Exceeding Expectations” awards for technical and team contributions. I believe in building not just software, but also a culture of excellence and innovation. Whether designing a user-centric front end or engineering high-performance backends, I bring a strategic, detail-oriented, and growth-focused mindset to every challenge.

  Let’s connect if you’re looking for someone who combines deep technical skills with leadership, innovation, and a relentless drive for results

content:
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: |
          - C#
          - JavaScript / TypeScript
          - Python
          - SQL
          - HTML5, CSS3
      - layout: left
        title: Frameworks & Libraries
        description: |
          - ASP.NET MVC / Web API
          - .NET Core
          - Entity Framework
          - React.js, Next.js
          - jQuery
      - layout: left
        title: Tools & Platforms
        description: |
          - Git & GitHub
          - Visual Studio, VS Code
          - Azure DevOps
          - Docker, Postman
      - layout: left
        title: Databases
        description: |
          - SQL Server
          - MySQL
      - layout: left
        title: Other Skills
        description: |
          - REST API Design
          - Agile & Scrum
          - Team Leadership & Mentoring
          - Code Review & Best Practices
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Bus Booking Engine
        link: https://www.nuego.in/
        link_text: Nuego Bus
        quote: >
          A comprehensive online platform for booking intercity bus tickets with real-time seat availability and secure payments.
        description: | 
          Developed and maintained core booking modules, user rights, reports, integrated payment gateways, and optimized APIs for faster search and booking experiences.
      - layout: left
        border: weak
        title: BT-SOFT
        link: https://academiaautozitania.pt/
        link_text: Autozitania Academy
        quote: >
          An integrated learning management and administrative system for e-training academies.
        description: | 
          Designed backend services, implemented user and course management features, implemented trainee/trainer/coordinator, and contributed to the automation of enrollment and progress tracking.
      - layout: left
        border: weak
        title: Petrol Pump Management System
        quote: >
          A digital solution to streamline operations, sales, and inventory management for petrol pumps.
        description: | 
          Built modules for daily sales tracking, inventory control, and financial reporting to improve operational efficiency.
      - layout: left
        border: weak
        title: PlayAmigos API
        link: https://play.google.com/store/apps/details?id=com.fedbidllc.playamigos&hl=en_IN&pli=1
        link_text: Play Amigos
        quote: >
          A robust API backend powering a social gaming platform that connects players for real-time multiplayer experiences.
        description: | 
          - Developed and maintained RESTful APIs, ensured scalability for high user loads, and integrated secure authentication mechanisms.
          - Convert the Express.js API to Nest.js as well.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Infinity Group of Companies
        sub_title: Senior Software Developer
        caption: 09/2021 - 02/2025
        link: https://infinityinfoway.com/
        description: | 
         - Led the design and development of scalable web applications using C# MVC and SQL Server.
         - Optimized API performance and implemented token management for secure communication.
         - Improved database queries for better performance and data integrity.
         - Worked closely with product managers, designers, and other developers to deliver high-quality features on time.
         - Played a key role in mentoring junior developers, guiding them through best practices and coding standards
      - layout: right
        title: Rebbitweb Technologies
        sub_title: Senior Software Developer
        caption: 04/2025 - Present
        link: 
        description: | 
          - Developed and maintained web applications using ASP.NET Zero, ASP.NET Core, MVC, and Web API
          - Built dynamic front-end components using JavaScript, jQuery, AJAX, and JSON
          - Collaborated with cross-functional teams to deliver features
          - Actively contributed to technical discussions and product improvement initiatives

  - title: Education
    layout: list
    content:
      - layout: top-center
        title: Shree Matrumandir Group of Colleges
        sub_title: Master of Science - MS, Information Technology
        caption: 05/2021 - 03/2023 
      - layout: top-center
        title: Atmiya Institute of Technology & Science
        sub_title: Bachelor of Science - BS, Information Technology
        caption: 05/2018 - 03/2021 

  - title: Awards
    layout: list
    content:
      - layout: left
        title: Shining Star
        caption: Infinity Group of Companies
        description: |
          Recognized for outstanding contributions and performance.
      - layout: left
        title: Exceeding Expectations Tech
        caption: Infinity Group of Companies
        description: |
          Awarded for delivering high-quality technical solutions and exceeding project expectations.

  - title: Licenses & Certifications
    layout: list
    content:
      - layout: left
        title: Power BI Workshop
        caption: United Latino Students Association
        description: |
          Hands-on training in business intelligence and data visualization using Power BI.
      - layout: left
        title: Back-End Web Development with .NET
        description: |
          Practical skills in building scalable server-side applications with .NET technologies.
      - layout: left
        title: Building a Website with Node.js and Express.js
        description: |
          Developed web applications using Node.js and Express.js frameworks.
      - layout: left
        title: Microsoft Azure - Identity and Access Management
        description: |
          Gained expertise in secure identity and access management solutions on Azure.
      - layout: left
        title: Hands-On Introduction - JavaScript
        description: |
          Built a strong foundation in modern JavaScript through practical, project-based learning.
      - layout: left
        title: SQL Practice - Intermediate Queries
        description: |
          Strengthened SQL query skills for database management and data analysis.
              
  - title: A Little More About Me
    layout: text
    content: | 
      Beyond my technical expertise, I am passionate about continuous learning and personal growth. I thrive in collaborative environments where innovation and teamwork drive success, and I enjoy mentoring others to help them reach their full potential. Outside of work, I am an avid learner who stays up-to-date with the latest industry trends, and I enjoy exploring new technologies and frameworks in my spare time. I also have a keen interest in productivity, leadership, and personal development, which inspires me to bring energy and positivity to every project I undertake.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
